version: "3.8"

volumes:
  mainnet-lite-volume:
    name: mainnet-lite-volume

services:
  monitor:
    image: subtensor-monitor:latest
    container_name: subtensor-monitor
    cap_add:
      - NET_ADMIN  # To allow firewall control
    volumes:
      - mainnet-lite-volume:/tmp/blockchain
      - /var/run/docker.sock:/var/run/docker.sock  # To control subtensor Docker containers
    network_mode: host
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - SUBTENSOR_CONTAINER_NAME=subtensor-mainnet-lite
      - SUBTENSOR_VOLUME_NAME=mainnet-lite-volume
      - LOCAL_URL=${LOCAL_URL}
      - FINNEY_URL=${FINNEY_URL}
      - SUBVORTEX_URL=${SUBVORTEX_URL}
    privileged: true
  subtensor-mainnet-lite:
    image: ghcr.io/opentensor/subtensor:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: subtensor
    cpu_count: 4
    mem_limit: 40000000000
    memswap_limit: 80000000000
    ports:
      - "9944:9944"
      - "30333:30333"
      - "9933:9933"
      - "9615:9615"
    expose:
      - "9944"
      - "30333"
      - "9933"
      - "9615"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    container_name: subtensor-mainnet-lite
    volumes:
      - mainnet-lite-volume:/tmp/blockchain
    command:
      - /bin/bash
      - -c
      - |
        node-subtensor \
          --base-path /tmp/blockchain \
          --chain raw_spec_finney.json \
          --rpc-external --rpc-cors all \
          --port 30333 \
          --rpc-port 9944 \
          --no-mdns \
          --in-peers 8000 --out-peers 8000 \
          --bootnodes /dns/bootnode.finney.chain.opentensor.ai/tcp/30333/ws/p2p/12D3KooWRwbMb85RWnT8DSXSYMWQtuDwh4LJzndoRrTDotTR5gDC \
          --sync warp \
          --prometheus-external
    networks:
      - subtensor_network

networks:
  subtensor_network:
    driver: bridge